name: MultiMC5-Release

on:
  push:
    branches:
      - develop
      - stable
      - CI
  pull_request:
    branches:
      - master
      - releases
      - CI

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest]
        
    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
        

          
      - name: Setup CMake
        run: |
          curl -L https://github.com/Kitware/CMake/releases/download/v3.20.2/cmake-3.20.2-windows-i386.msi -o cmake.msi && ./cmake.msi /quiet
      
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '8'
          architecture: x86
      
      - name: Setup zlib
        run: |
          mkdir zlib && curl https://razaoinfo.dl.sourceforge.net/project/gnuwin32/zlib/1.2.3/zlib-1.2.3-bin.zip -o zlib.zip && unzip zlib.zip && cd .. && pwd
          
      - name: Setup PATH
        shell: cmd
        run: |
          set PATH=C:\Users\runneradmin\Qt\Qt5.6.0\5.6\mingw49_32\bin;C:\Users\runneradmin\Qtr\Qt5.6.0\Tools\mingw492_32\bin;%PATH%
          set PATH=%CD%\zlib;%CD%\zlib\bin;%PATH%
          set PATH=C:\hostedtoolcache\windows\Java_Zulu_jdk\8.0.292-10\x86\bin;%PATH%
          java --version
          cmake --version
