name: MultiMC5-Release

on:
  push:
    branches:
      - develop
      - stable
      - CI
  pull_request:
    branches:
      - master
      - releases
      - CI

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest]
        
    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - name: Creates QtAccount File
        uses: DamianReeves/write-file-action@v1.0
        with:
          # The path to the file to write
          path: "%APPDATA%\\Qt"
          # The contents of the file
          contents: ${{ secrets.QTACCOUNT }}
                    
      - name: Echo and PWD test
        shell: cmd
        run: echo "%APPDATA%\\Qt"
      
      - name: Download QT Installer
        run: |
          curl https://download.qt.io/new_archive/qt/5.6/5.6.3/qt-opensource-windows-x86-mingw492-5.6.3.exe --output installer.exe
          
      - name: Cache
        uses: actions/cache@v2.1.5
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: "installer.exe"
          # An explicit key for restoring and saving the cache
          key: ${{ runner.os }}-qt56-installer
