name: MultiMC5-Release

on:
  push:
    branches:
      - develop
      - stable
      - CI
  pull_request:
    branches:
      - master
      - releases
      - CI

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest]
        
    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - name: Install QT
        uses: jurplel/install-qt-action@v2.13.2
        with:
          # Directory to install Qt
          #dir: # optional
          # Version of Qt to install
          version: 5.6_preview # optional, default is 5.15.2
          # Host platform
          host: windows # optional
          # Target platform for build
          target: desktop # optional, default is desktop
          # Architecture for Windows/Android
          arch: win32_mingw49 # optional
