name: MultiMC5-Release

on:
  push:
    branches:
      - develop
      - stable
      - CI
  pull_request:
    branches:
      - master
      - releases
      - CI

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest]
        
    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - name: Creates QtAccount File
        uses: DamianReeves/write-file-action@v1.0
        with:
          # The path to the file to write
          path: "%APPDATA%\\Qt"
          # The contents of the file
          contents: ${{ secrets.QTACCOUNT }}
          
      - name: File Reader
        # You may pin to the exact commit or the version.
        # uses: andstor/file-reader-action@babb053761401147562e75be79d832978cc97325
        uses: andstor/file-reader-action@v1.0.0
        with:
          # The path to the file to be read.
          path: "%APPDATA%\\Qt"
          
      - name: Echo and PWD test
        shell: cmd
        run: echo "%APPDATA%\\Qt"
      
      - name: Install QT
        uses: jurplel/install-qt-action@v2.13.2
        with:
          # Directory to install Qt
          #dir: # optional
          # Version of Qt to install
          version: 5.6_preview # optional, default is 5.15.2
          # Host platform
          host: windows # optional
          # Target platform for build
          target: desktop # optional, default is desktop
          # Architecture for Windows/Android
          arch: win32_mingw49 # optional
